export { default as ProyekTable } from '@/Components/Dashboard/DirekturUtama/ProyekTable.vue'
export { default as SisaDanaRekeningTable } from '@/Components/Dashboard/DirekturUtama/SisaDanaRekeningTable.vue'
export { default as ProyeksiInvoiceProyekTable } from '@/Components/Dashboard/DirekturUtama/ProyeksiInvoiceProyekTable.vue'
export { default as ProyeksiKebutuhanDanaProyekTable } from '@/Components/Dashboard/DirekturUtama/ProyeksiKebutuhanDanaProyekTable.vue'
export { default as ProyeksiUtangTable } from '@/Components/Dashboard/DirekturUtama/ProyeksiUtangTable.vue'
export { default as ProyeksiPiutangTable } from '@/Components/Dashboard/DirekturUtama/ProyeksiPiutangTable.vue'
