export { default as ProyekTable } from '@/Components/Dashboard/Admin/ProyekTable.vue'
export { default as SisaDanaRekeningTable } from '@/Components/Dashboard/Admin/SisaDanaRekeningTable.vue'
export { default as ProyeksiInvoiceProyekTable } from '@/Components/Dashboard/Admin/ProyeksiInvoiceProyekTable.vue'
export { default as ProyeksiKebutuhanDanaProyekTable } from '@/Components/Dashboard/Admin/ProyeksiKebutuhanDanaProyekTable.vue'
export { default as ProyeksiUtangTable } from '@/Components/Dashboard/Admin/ProyeksiUtangTable.vue'
export { default as ProyeksiPiutangTable } from '@/Components/Dashboard/Admin/ProyeksiPiutangTable.vue'
export { default as ProyeksiSetoranModalTable } from '@/Components/Dashboard/Admin/ProyeksiSetoranModalTable.vue'
export { default as ProyeksiPenarikanTable } from '@/Components/Dashboard/Admin/ProyeksiPenarikanTable.vue'
